name: demo1
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^5.7.10
  flutter_webview_plugin: ^0.3.11
  date_format: ^1.0.9
  shared_preferences: ^0.5.12+4
  dio: ^3.0.10
  flutter_spinkit: ^4.1.2+1
  fluttertoast: ^7.1.5
  flutter_screenutil: ^3.2.0
  flutter_swiper : ^1.1.6
  provider: ^4.3.2+3
  gbk2utf8: ^1.0.1
  flutter_easyrefresh: ^2.1.7
  flutter_custom_dialog: ^1.0.20
  pull_to_refresh: ^1.6.3
  fbutton: ^2.0.1
  fradio: ^1.0.1
  fsuper: ^2.0.2
  flustars: ^0.3.3
  common_utils: ^1.2.1
  extended_image: ^1.3.0
  extended_image_library: ^0.3.1
  waterfall_flow: ^2.0.5
  loading_more_list: ^3.1.1
  extended_list: ^2.0.2
  pull_to_refresh_notification: ^1.1.2
  shimmer: ^1.1.2
  flutter_svg: 0.18.1
  extended_text_field: ^5.0.2
  extended_text: ^4.1.0
  flutter_emoji: ^2.2.1+1
  html: ^0.14.0+4
  image_picker: ^0.6.7+14
  extended_tabs: ^0.2.3
  luhenchang_plugin: ^0.1.2
  nav_router: ^0.0.7
#  flutter_alibc: ^0.0.15 # 淘宝登录
  after_layout: ^1.0.7+2
  palette_generator: ^0.2.3
  crypto: ^2.1.5
  encrypt: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
     - assets/images/
     - assets/nav/
     - assets/icons/
     - assets/svg/
     - assets/json/

